# Property search settings
search_area_granularity: район
area_search_radius: 100
debug_search_radius: 100

# Processing settings
daily_check_enabled: true
gpt_analysis_enabled: true
advantage_price_threshold: -30
market_yield_threshold: 10 


# GPT prompt template
gpt_prompt_template: |
  Вы эксперт по классификации недвижимости. На основе описания и характеристик объекта, классифицируйте его в одну из следующих категорий:

  1. Стрит-ритейл (с входом с улицы):
     - 70-120 м²
     - 120-250 м²
     - 250-500 м²
     - 500-1000 м²
     - 1000-1500 м²
     - 1500+ м²

  2. Офисы:
     - 1000-3500 м²

  3. Отдельно стоящее здание:
     - Любой размер

  4. Промышленные помещения:
     - До 1000 м²
     - 1000-3000 м²
     - 3000-5000 м²

  5. Коммерческая земля:
     - От 1 га

  Дополнительно укажите:
  - Есть ли упоминание о подвале или полуподвале
  - Есть ли указания, что это верхний этаж (ключевые слова: "последний этаж", "верхний этаж", "мансарда")

  Детали объекта:
  - Название: {name}
  - Описание: {description}
  - Площадь: {area} м²
  - Категория недвижимости: {category}

  Представьте свой ответ в формате JSON:
  {{"category": "название_категории", "size_category": "диапазон_размера", "has_basement": true/false, "is_top_floor": true/false}}