# Property search settings
search_area_granularity: район
area_search_radius: 7
debug_search_radius: 7

# Processing settings
daily_check_enabled: true
gpt_analysis_enabled: true
advantage_price_threshold: -30
market_yield_threshold: 10 


# GPT prompt templates
gpt_prompt_template: |
  Вы эксперт по классификации недвижимости. На основе описания и характеристик объекта, классифицируйте его в одну из следующих категорий:

  1. Стрит-ритейл (с входом с улицы):
     - 70-120 м²
     - 120-250 м²
     - 250-500 м²
     - 500-1000 м²
     - 1000-1500 м²
     - 1500+ м²

  2. Офисы:
     - 1000-3500 м²

  3. Отдельно стоящее здание:
     - Любой размер

  4. Промышленные помещения:
     - До 1000 м²
     - 1000-3000 м²
     - 3000-5000 м²

  5. Коммерческая земля:
     - От 1 га

  Дополнительно укажите:
  - Есть ли упоминание о подвале или полуподвале
  - Есть ли указания, что это верхний этаж (ключевые слова: "последний этаж", "верхний этаж", "мансарда")

  Детали объекта:
  - Название: {name}
  - Описание: {description}
  - Площадь: {area} м²
  - Категория недвижимости: {category}

  Представьте свой ответ в формате JSON:
  {{"category": "название_категории", "size_category": "диапазон_размера", "has_basement": true/false, "is_top_floor": true/false}}

# Шаблон для расчета финансовых метрик объекта
gpt_metrics_template: |
  Вы финансовый аналитик, специализирующийся на оценке коммерческой недвижимости. Ваша задача — рассчитать финансовые показатели объекта на основе предоставленных данных.

  ДАННЫЕ ОБЪЕКТА:
  - ID: {lot_id}
  - Наименование: {name}
  - Площадь: {area} м²
  - Цена: {price} ₽
  - Район: {district}
  - Категория: {category}

  РЫНОЧНЫЕ ДАННЫЕ:
  - Медианная цена продажи в районе: {market_price_per_sqm} ₽/м²
  - Медианная арендная ставка в районе: {avg_rent_price_per_sqm} ₽/м²/месяц
  - Количество объявлений о продаже: {sale_offers_count}
  - Количество объявлений об аренде: {rent_offers_count}

  РАССЧИТАЙТЕ:
  1. Рыночная стоимость объекта (₽) = Медианная цена продажи × Площадь
  2. Капитализация (₽) = Рыночная стоимость - Цена объекта
  3. Капитализация (%) = (Капитализация в ₽ / Цена объекта) × 100%
  4. Месячный GAP (арендный поток в ₽/месяц) = Медианная арендная ставка × Площадь
     - Если данных об аренде нет, используйте формулу: Рыночная стоимость × 0.007
  5. Годовой доход (₽) = Месячный GAP × 12
  6. Годовая доходность (%) = (Годовой доход / Цена объекта) × 100%
  7. Плюсы:
     - Плюс за продажу: 1 если Капитализация (%) ≥ 0, иначе 0
     - Плюс за аренду: 1 если Годовая доходность (%) ≥ 10, иначе 0
  8. Общее количество плюсов = Плюс за продажу + Плюс за аренду
  9. Статус объекта:
     - "approved" если 2 плюса
     - "review" если 1 плюс
     - "discard" если 0 плюсов

  Если данных о продаже или аренде недостаточно, сделайте пометку об этом.

  Ответ представьте в JSON-формате:
  {
    "market_price_per_sqm": число,
    "market_value": число,
    "capitalization_rub": число,
    "capitalization_percent": число,
    "monthly_gap": число,
    "annual_income": число,
    "annual_yield_percent": число,
    "plus_sale": 0 или 1,
    "plus_rental": 0 или 1,
    "plus_count": число,
    "status": "approved", "review" или "discard",
    "has_rent_data": true или false,
    "market_value_method": "sales" или "none"
  }